VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname ="dockhouse-dev"

  config.vm.provision :shell, :inline => "sudo apt-get update"

  # Docker installation
  config.vm.provision :shell, :inline => "sudo apt-get install -y curl; curl -s http://get.docker.io/ubuntu/ | sudo sh"
  config.vm.provision :shell, :inline => 'sudo echo DOCKER_OPTS=\"--dns 8.8.8.8 --dns 8.8.4.4 --insecure-registry 192.168.29.100:5000\" >> /etc/default/docker'

  # Add vagrant to the docker user group
  config.vm.provision :shell, :inline => "sudo gpasswd -a vagrant docker"
  config.vm.provision :shell, :inline => "sudo service docker restart"

  # Docker compose installation
  config.vm.provision :shell, :inline => "curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
  config.vm.provision :shell, :inline => "chmod +x /usr/local/bin/docker-compose"
  config.vm.provision :shell, :inline => "curl -L https://raw.githubusercontent.com/docker/compose/1.1.0/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"

  # Copy the scripts to launch the Dockhouse dev environment"
  config.vm.provision "file", source: "./scripts", destination: "scripts"
  config.vm.provision :shell, :inline => "chmod +x ./scripts/create-image-in-registry.sh"


  # Network configuration
  config.vm.network :private_network, ip:"192.168.29.100"
  # Port for MongoDB
  config.vm.network :forwarded_port, guest: 27017, host: 27017
  # Port for registry
  config.vm.network :forwarded_port, guest: 5000, host: 5000
end
